//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CHITIETDDH
{
    public string MADDH { get; set; }
    public string MASP { get; set; }
    public Nullable<int> SOLUONG { get; set; }

    public virtual SAN_PHAM SAN_PHAM { get; set; }
}

public partial class CHITIETHD
{
    public string MAHD { get; set; }
    public string MASP { get; set; }
    public int SOLUONG { get; set; }

    public virtual HOA_DON HOA_DON { get; set; }
    public virtual SAN_PHAM SAN_PHAM { get; set; }
}

public partial class CONG_TY
{
    public string MACTY { get; set; }
    public string TENCTY { get; set; }
    public string DIACHICT { get; set; }
    public string SDTCT { get; set; }
    public string MOTACT { get; set; }
    public string WEBSITECT { get; set; }
    public string MASOTHUE { get; set; }
    public string FAX { get; set; }
    public string LINHVUC { get; set; }
    public string EMAILCT { get; set; }
}

public partial class DM_MANHINH
{
    public DM_MANHINH()
    {
        this.QL_NGUOIDUNGNHOMNGUOIDUNG = new HashSet<QL_NGUOIDUNGNHOMNGUOIDUNG>();
    }

    public string MAMANHINH { get; set; }
    public string TENMANHINH { get; set; }

    public virtual ICollection<QL_NGUOIDUNGNHOMNGUOIDUNG> QL_NGUOIDUNGNHOMNGUOIDUNG { get; set; }
}

public partial class DONDATHANG
{
    public string MADDH { get; set; }
    public string MAKH { get; set; }
    public Nullable<double> TONGTIENMUA { get; set; }
    public Nullable<System.DateTime> NGAYDATHANG { get; set; }
    public string GHICHUNND { get; set; }
    public string DIACHINHANHANG { get; set; }

    public virtual KHACH_HANG KHACH_HANG { get; set; }
}

public partial class DSHANGCHUYENKHO
{
    public string MAPC { get; set; }
    public string MASP { get; set; }
    public Nullable<int> SL { get; set; }

    public virtual PHIEU_CHUYEN PHIEU_CHUYEN { get; set; }
    public virtual SAN_PHAM SAN_PHAM { get; set; }
}

public partial class DSHANGNHAP
{
    public string MAPN { get; set; }
    public string MASP { get; set; }
    public Nullable<int> SL { get; set; }
    public Nullable<double> ThanhTien { get; set; }

    public virtual PHIEU_NHAP PHIEU_NHAP { get; set; }
    public virtual SAN_PHAM SAN_PHAM { get; set; }
}

public partial class DSHANGXUAT
{
    public string MAPX { get; set; }
    public string MASP { get; set; }
    public Nullable<int> SoLuong { get; set; }
    public Nullable<double> ThanhTien { get; set; }

    public virtual PHIEU_XUAT PHIEU_XUAT { get; set; }
    public virtual SAN_PHAM SAN_PHAM { get; set; }
}

public partial class HANGTON
{
    public string MAKHO { get; set; }
    public string MASP { get; set; }
    public Nullable<int> SOLUONG { get; set; }

    public virtual KHOHANG KHOHANG { get; set; }
    public virtual SAN_PHAM SAN_PHAM { get; set; }
}

public partial class HOA_DON
{
    public HOA_DON()
    {
        this.CHITIETHDs = new HashSet<CHITIETHD>();
    }

    public string MAHD { get; set; }
    public string MAKH { get; set; }
    public Nullable<System.DateTime> NGAYLAP { get; set; }
    public Nullable<double> TONGTIENMUA { get; set; }

    public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
    public virtual KHACH_HANG KHACH_HANG { get; set; }
}

public partial class KHACH_HANG
{
    public KHACH_HANG()
    {
        this.DONDATHANGs = new HashSet<DONDATHANG>();
        this.HOA_DON = new HashSet<HOA_DON>();
    }

    public string MAKH { get; set; }
    public string TENKH { get; set; }
    public string SDTKH { get; set; }
    public string EMAILKH { get; set; }
    public string DIACHIKH { get; set; }

    public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
    public virtual ICollection<HOA_DON> HOA_DON { get; set; }
}

public partial class KHOHANG
{
    public KHOHANG()
    {
        this.HANGTONs = new HashSet<HANGTON>();
        this.PHIEU_CHUYEN = new HashSet<PHIEU_CHUYEN>();
        this.PHIEU_CHUYEN1 = new HashSet<PHIEU_CHUYEN>();
        this.PHIEU_NHAP = new HashSet<PHIEU_NHAP>();
        this.PHIEU_XUAT = new HashSet<PHIEU_XUAT>();
    }

    public string MAKHO { get; set; }
    public string TENKHO { get; set; }
    public string DIACHIKHO { get; set; }
    public string MOTA { get; set; }

    public virtual ICollection<HANGTON> HANGTONs { get; set; }
    public virtual ICollection<PHIEU_CHUYEN> PHIEU_CHUYEN { get; set; }
    public virtual ICollection<PHIEU_CHUYEN> PHIEU_CHUYEN1 { get; set; }
    public virtual ICollection<PHIEU_NHAP> PHIEU_NHAP { get; set; }
    public virtual ICollection<PHIEU_XUAT> PHIEU_XUAT { get; set; }
}

public partial class KHU_VUC
{
    public KHU_VUC()
    {
        this.NHA_CUNG_CAP = new HashSet<NHA_CUNG_CAP>();
    }

    public string MAKV { get; set; }
    public string TENKV { get; set; }
    public string MOTA { get; set; }

    public virtual ICollection<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
}

public partial class LOAI_SAN_PHAM
{
    public LOAI_SAN_PHAM()
    {
        this.SAN_PHAM = new HashSet<SAN_PHAM>();
    }

    public string MALOAI { get; set; }
    public string TENLOAI { get; set; }
    public string MOTALSP { get; set; }

    public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }
}

public partial class NHA_CUNG_CAP
{
    public NHA_CUNG_CAP()
    {
        this.SAN_PHAM = new HashSet<SAN_PHAM>();
    }

    public string MANCC { get; set; }
    public string MAKV { get; set; }
    public string TENNCC { get; set; }
    public string DIACHINCC { get; set; }
    public string NGUOILIENHE { get; set; }
    public string SDTNCC { get; set; }
    public string MOTANCC { get; set; }
    public string EMAILNCC { get; set; }
    public string WEBSITENCC { get; set; }

    public virtual KHU_VUC KHU_VUC { get; set; }
    public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }
}

public partial class NHA_SAN_XUAT
{
    public NHA_SAN_XUAT()
    {
        this.SAN_PHAM = new HashSet<SAN_PHAM>();
    }

    public string MANSX { get; set; }
    public string TENNSX { get; set; }
    public string MOTANSX { get; set; }
    public string EMAILNSX { get; set; }
    public string WEBSITENSX { get; set; }

    public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }
}

public partial class NHAN_VIEN
{
    public NHAN_VIEN()
    {
        this.PHIEU_CHUYEN = new HashSet<PHIEU_CHUYEN>();
        this.PHIEU_NHAP = new HashSet<PHIEU_NHAP>();
        this.PHIEU_XUAT = new HashSet<PHIEU_XUAT>();
    }

    public string MANV { get; set; }
    public string TENNV { get; set; }
    public string GIOITINH { get; set; }
    public string DIACHINV { get; set; }
    public string SDTNV { get; set; }

    public virtual ICollection<PHIEU_CHUYEN> PHIEU_CHUYEN { get; set; }
    public virtual ICollection<PHIEU_NHAP> PHIEU_NHAP { get; set; }
    public virtual ICollection<PHIEU_XUAT> PHIEU_XUAT { get; set; }
}

public partial class PHIEU_CHUYEN
{
    public PHIEU_CHUYEN()
    {
        this.DSHANGCHUYENKHOes = new HashSet<DSHANGCHUYENKHO>();
    }

    public string MAPC { get; set; }
    public Nullable<System.DateTime> NGAYCHUYEN { get; set; }
    public string TUKHO { get; set; }
    public string DENKHO { get; set; }
    public string MANV { get; set; }
    public Nullable<double> TONGTIEN { get; set; }
    public string LYDO { get; set; }

    public virtual ICollection<DSHANGCHUYENKHO> DSHANGCHUYENKHOes { get; set; }
    public virtual KHOHANG KHOHANG { get; set; }
    public virtual KHOHANG KHOHANG1 { get; set; }
    public virtual NHAN_VIEN NHAN_VIEN { get; set; }
}

public partial class PHIEU_NHAP
{
    public PHIEU_NHAP()
    {
        this.DSHANGNHAPs = new HashSet<DSHANGNHAP>();
    }

    public string MAPN { get; set; }
    public string MANV { get; set; }
    public Nullable<System.DateTime> NGAYNHAP { get; set; }
    public string NOIDUNG { get; set; }
    public string MAKHO { get; set; }

    public virtual ICollection<DSHANGNHAP> DSHANGNHAPs { get; set; }
    public virtual KHOHANG KHOHANG { get; set; }
    public virtual NHAN_VIEN NHAN_VIEN { get; set; }
}

public partial class PHIEU_XUAT
{
    public PHIEU_XUAT()
    {
        this.DSHANGXUATs = new HashSet<DSHANGXUAT>();
    }

    public string MAPX { get; set; }
    public string MANV { get; set; }
    public Nullable<System.DateTime> NGAYXUAT { get; set; }
    public string MOTAPHIEUXUAT { get; set; }
    public string MAKHO { get; set; }

    public virtual ICollection<DSHANGXUAT> DSHANGXUATs { get; set; }
    public virtual KHOHANG KHOHANG { get; set; }
    public virtual NHAN_VIEN NHAN_VIEN { get; set; }
}

public partial class QL_NGUOIDUNG
{
    public QL_NGUOIDUNG()
    {
        this.QL_PHANQUYEN = new HashSet<QL_PHANQUYEN>();
    }

    public string TENDANGNHAP { get; set; }
    public string MATKHAU { get; set; }
    public Nullable<byte> HOATDONG { get; set; }

    public virtual ICollection<QL_PHANQUYEN> QL_PHANQUYEN { get; set; }
}

public partial class QL_NGUOIDUNGNHOMNGUOIDUNG
{
    public string MANHOM { get; set; }
    public string MAMANHINH { get; set; }
    public string GHICHUNND { get; set; }

    public virtual DM_MANHINH DM_MANHINH { get; set; }
    public virtual QL_NHOMNGUOIDUNG QL_NHOMNGUOIDUNG { get; set; }
}

public partial class QL_NHOMNGUOIDUNG
{
    public QL_NHOMNGUOIDUNG()
    {
        this.QL_NGUOIDUNGNHOMNGUOIDUNG = new HashSet<QL_NGUOIDUNGNHOMNGUOIDUNG>();
        this.QL_PHANQUYEN = new HashSet<QL_PHANQUYEN>();
    }

    public string MANHOM { get; set; }
    public string TENNHOM { get; set; }
    public string GHICHUNND { get; set; }

    public virtual ICollection<QL_NGUOIDUNGNHOMNGUOIDUNG> QL_NGUOIDUNGNHOMNGUOIDUNG { get; set; }
    public virtual ICollection<QL_PHANQUYEN> QL_PHANQUYEN { get; set; }
}

public partial class QL_PHANQUYEN
{
    public string TENDANGNHAP { get; set; }
    public string MANHOM { get; set; }
    public Nullable<bool> COQUYEN { get; set; }

    public virtual QL_NGUOIDUNG QL_NGUOIDUNG { get; set; }
    public virtual QL_NHOMNGUOIDUNG QL_NHOMNGUOIDUNG { get; set; }
}

public partial class SAN_PHAM
{
    public SAN_PHAM()
    {
        this.CHITIETDDHs = new HashSet<CHITIETDDH>();
        this.CHITIETHDs = new HashSet<CHITIETHD>();
        this.DSHANGCHUYENKHOes = new HashSet<DSHANGCHUYENKHO>();
        this.DSHANGNHAPs = new HashSet<DSHANGNHAP>();
        this.DSHANGXUATs = new HashSet<DSHANGXUAT>();
        this.HANGTONs = new HashSet<HANGTON>();
    }

    public string MASP { get; set; }
    public string MALOAI { get; set; }
    public string MANCC { get; set; }
    public string MANSX { get; set; }
    public string TEN_SP { get; set; }
    public string MAUSAC { get; set; }
    public Nullable<double> GIANHAP { get; set; }
    public Nullable<double> GIABANSI { get; set; }
    public Nullable<double> GIABANLE { get; set; }
    public string DVT { get; set; }
    public string MOTASP { get; set; }
    public string HinhAnh { get; set; }

    public virtual ICollection<CHITIETDDH> CHITIETDDHs { get; set; }
    public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
    public virtual ICollection<DSHANGCHUYENKHO> DSHANGCHUYENKHOes { get; set; }
    public virtual ICollection<DSHANGNHAP> DSHANGNHAPs { get; set; }
    public virtual ICollection<DSHANGXUAT> DSHANGXUATs { get; set; }
    public virtual ICollection<HANGTON> HANGTONs { get; set; }
    public virtual LOAI_SAN_PHAM LOAI_SAN_PHAM { get; set; }
    public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    public virtual NHA_SAN_XUAT NHA_SAN_XUAT { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class TKKHO_VIEW
{
    public string TEN_SP { get; set; }
    public string DVT { get; set; }
    public Nullable<int> SLNHAP { get; set; }
    public Nullable<int> SLXUAT { get; set; }
    public Nullable<int> SLTON { get; set; }
    public string MAKHO { get; set; }
    public Nullable<double> GIANHAP { get; set; }
    public Nullable<double> GIABANLE { get; set; }
    public Nullable<double> GIABANSI { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
