<?xml version="1.0" encoding="utf-8"?><Database Name="QLKHO" Class="SanPhamDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-IF5SHKQ\SQLEXPRESS;Initial Catalog=QLKHO;Integrated Security=True" SettingsObjectName="DAL_BLL.Properties.Settings" SettingsPropertyName="QLKHOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETDDH" Member="CHITIETDDHs">
    <Type Name="CHITIETDDH">
      <Column Name="MADDH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDDH" Member="DONDATHANG" ThisKey="MADDH" OtherKey="MADDH" Type="DONDATHANG" IsForeignKey="true" />
      <Association Name="SAN_PHAM_CHITIETDDH" Member="SAN_PHAM" ThisKey="MASP" OtherKey="MASP" Type="SAN_PHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DM_MANHINH" Member="DM_MANHINHs">
    <Type Name="DM_MANHINH">
      <Column Name="MAMANHINH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMANHINH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MADDH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TONGTIENMUA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NGAYDATHANG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GHICHUNND" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DIACHINHANHANG" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDDH" Member="CHITIETDDHs" ThisKey="MADDH" OtherKey="MADDH" Type="CHITIETDDH" />
      <Association Name="KHACH_HANG_DONDATHANG" Member="KHACH_HANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACH_HANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOA__ON" Member="HOA__ONs">
    <Type Name="HOA__ON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIENMUA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HOA__ON_PHIEU_XUAT" Member="PHIEU_XUATs" ThisKey="MAHD" OtherKey="MAHD" Type="PHIEU_XUAT" />
      <Association Name="HOA__ON_SAN_PHAM" Member="SAN_PHAMs" ThisKey="MAHD" OtherKey="MAHD" Type="SAN_PHAM" />
      <Association Name="KHACH_HANG_HOA__ON" Member="KHACH_HANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACH_HANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACH_HANG" Member="KHACH_HANGs">
    <Type Name="KHACH_HANG">
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SDTKH" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAILKH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIACHIKH" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="KHACH_HANG_DONDATHANG" Member="DONDATHANGs" ThisKey="MAKH" OtherKey="MAKH" Type="DONDATHANG" />
      <Association Name="KHACH_HANG_HOA__ON" Member="HOA__ONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOA__ON" />
    </Type>
  </Table>
  <Table Name="dbo.KHU_VUC" Member="KHU_VUCs">
    <Type Name="KHU_VUC">
      <Column Name="MAKV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKV" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="KHU_VUC_NHA_CUNG_CAP" Member="NHA_CUNG_CAPs" ThisKey="MAKV" OtherKey="MAKV" Type="NHA_CUNG_CAP" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_SAN_PHAM" Member="LOAI_SAN_PHAMs">
    <Type Name="LOAI_SAN_PHAM">
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOMSP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MOTALSP" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="LOAI_SAN_PHAM_SAN_PHAM" Member="SAN_PHAMs" ThisKey="MALOAI" OtherKey="MALOAI" Type="SAN_PHAM" />
      <Association Name="NHOM_SAN_PHAM_LOAI_SAN_PHAM" Member="NHOM_SAN_PHAM" ThisKey="MANHOMSP" OtherKey="MANHOMSP" Type="NHOM_SAN_PHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHA_CUNG_CAP" Member="NHA_CUNG_CAPs">
    <Type Name="NHA_CUNG_CAP">
      <Column Name="MANCC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIACHINCC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NGUOILIENHE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SDTNCC" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MOTANCC" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="EMAILNCC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WEBSITENCC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="NHA_CUNG_CAP_SAN_PHAM" Member="SAN_PHAMs" ThisKey="MANCC" OtherKey="MANCC" Type="SAN_PHAM" />
      <Association Name="KHU_VUC_NHA_CUNG_CAP" Member="KHU_VUC" ThisKey="MAKV" OtherKey="MAKV" Type="KHU_VUC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHAN_VIEN" Member="NHAN_VIENs">
    <Type Name="NHAN_VIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MACTY" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="DIACHINV" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SDTNV" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Association Name="NHAN_VIEN_PHIEU_NHAP" Member="PHIEU_NHAPs" ThisKey="MANV" OtherKey="MANV" Type="PHIEU_NHAP" />
      <Association Name="NHAN_VIEN_PHIEU_XUAT" Member="PHIEU_XUATs" ThisKey="MANV" OtherKey="MANV" Type="PHIEU_XUAT" />
      <Association Name="QL_NGUOIDUNG_NHAN_VIEN" Member="QL_NGUOIDUNG" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG" IsForeignKey="true" />
      <Association Name="CONG_TY_NHAN_VIEN" Member="CONG_TY" ThisKey="MACTY" OtherKey="MACTY" Type="CONG_TY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHA_SAN_XUAT" Member="NHA_SAN_XUATs">
    <Type Name="NHA_SAN_XUAT">
      <Column Name="MANSX" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNSX" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MOTANSX" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="EMAILNSX" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WEBSITENSX" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="NHA_SAN_XUAT_SAN_PHAM" Member="SAN_PHAMs" ThisKey="MANSX" OtherKey="MANSX" Type="SAN_PHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHOM_SAN_PHAM" Member="NHOM_SAN_PHAMs">
    <Type Name="NHOM_SAN_PHAM">
      <Column Name="MANHOMSP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOMSP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MOTANSP" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="NHOM_SAN_PHAM_LOAI_SAN_PHAM" Member="LOAI_SAN_PHAMs" ThisKey="MANHOMSP" OtherKey="MANHOMSP" Type="LOAI_SAN_PHAM" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEU_NHAP" Member="PHIEU_NHAPs">
    <Type Name="PHIEU_NHAP">
      <Column Name="MAPN" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOIDUNG" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="NHAN_VIEN_PHIEU_NHAP" Member="NHAN_VIEN" ThisKey="MANV" OtherKey="MANV" Type="NHAN_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG" Member="QL_NGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_NHAN_VIEN" Member="NHAN_VIENs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="NHAN_VIEN" />
      <Association Name="QL_NGUOIDUNG_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEU_XUAT" Member="PHIEU_XUATs">
    <Type Name="PHIEU_XUAT">
      <Column Name="MAPX" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYXUAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOTAPHIEUXUAT" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="NHAN_VIEN_PHIEU_XUAT" Member="NHAN_VIEN" ThisKey="MANV" OtherKey="MANV" Type="NHAN_VIEN" IsForeignKey="true" />
      <Association Name="HOA__ON_PHIEU_XUAT" Member="HOA__ON" ThisKey="MAHD" OtherKey="MAHD" Type="HOA__ON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs">
    <Type Name="QL_NGUOIDUNGNHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMANHINH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHUNND" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="DM_MANHINH" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="DM_MANHINH" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNGs">
    <Type Name="QL_NHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GHICHUNND" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PHANQUYEN" Member="QL_PHANQUYENs">
    <Type Name="QL_PHANQUYEN">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_QL_PHANQUYEN" Member="QL_NGUOIDUNG" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SAN_PHAM" Member="SAN_PHAMs">
    <Type Name="SAN_PHAM">
      <Column Name="MASP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANSX" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_SAN_" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="MAUSAC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KICHTHUOC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GIANHAP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GIABANSI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GIABANLE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MOTASP" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="SAN_PHAM_CHITIETDDH" Member="CHITIETDDHs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETDDH" />
      <Association Name="LOAI_SAN_PHAM_SAN_PHAM" Member="LOAI_SAN_PHAM" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAI_SAN_PHAM" IsForeignKey="true" />
      <Association Name="NHA_CUNG_CAP_SAN_PHAM" Member="NHA_CUNG_CAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHA_CUNG_CAP" IsForeignKey="true" />
      <Association Name="NHA_SAN_XUAT_SAN_PHAM" Member="NHA_SAN_XUAT" ThisKey="MANSX" OtherKey="MANSX" Type="NHA_SAN_XUAT" IsForeignKey="true" />
      <Association Name="HOA__ON_SAN_PHAM" Member="HOA__ON" ThisKey="MAHD" OtherKey="MAHD" Type="HOA__ON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONG_TY" Member="CONG_Ties">
    <Type Name="CONG_TY">
      <Column Name="MACTY" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCTY" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DIACHICT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SDTCT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MOTACT" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="WEBSITECT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="CONG_TY_NHAN_VIEN" Member="NHAN_VIENs" ThisKey="MACTY" OtherKey="MACTY" Type="NHAN_VIEN" />
    </Type>
  </Table>
</Database>